name:                Wumpus
version:             0.1.0.0
github:              "githubuser/Wumpus"
license:             BSD3
author:              "Brendan Van Allen & Kyle Burns"
maintainer:          "brendan.vanallen1@marist.edu"
copyright:           "2018 Brendan Van Allen"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/Wumpus#readme>

dependencies:
- base >= 4.7 && < 5
- random
- process

library:
  source-dirs: src

executables:
  Wumpus-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Wumpus

tests:
  Wumpus-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Wumpus
